server:
    port: 9090
    context-path: /a

logging:
    level:
        root: debug
        com.loushuiyifan.shiro.cache.EhcacheManagerWrapper: info
        net.sf.ehcache: info
        org.springframework: info
        org.apache: info
        org.apache.shiro: debug


spring:
    mvc:
        view:
            prefix: /templates/
            suffix: .html

    thymeleaf:
        enabled: true
        cache: false
        mode: LEGACYHTML5
        encoding: UTF-8
        content-type: text/html
        check-template-location: true
        check-template: false

    datasource:
        url: jdbc:mysql://localhost:3306/aweb
        username: root
        password: root
        druid:
            initial-size: 1
            min-idle: 1
            max-active: 20
            max-wait: 60000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            filter: stat,wall
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            use-global-data-source-stat: true
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: root
                login-password: root
                reset-enable: false
                allow: 127.0.0.1
            web-stat-filter:
                enabled: true
                exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"


mybatis:
    type-aliases-package: com.loushuiyifan.mybatis.bean
    mapper-locations: classpath*:mapper/*.xml

mapper:
    mappers:
        - com.loushuiyifan.mybatis.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql