server:
    port: 8080
    context-path: /a

report:
  storage:
    location: /report/files
    image: /report/files/image
    report-upload-template: /report/files/reportUploadTemplate
    report-upload: /report/files/reportUpload
    report-download-template: /report/files/reportDownloadTemplate
    report-download: /report/files/reportDownload

logging:
    level:
        root: info
        com.loushuiyifan: debug
        com.loushuiyifan.config: info
        net.sf.ehcache: info
        org.eclipse: info
        org.mybatis: info
        org.springframework.jdbc: debug
        org.apache: info
#    file: /report/logs/my.log


spring:
    http:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    aop:
      proxy-target-class: true
    thymeleaf:
          cache: false
    output:
        ansi:
          enabled: always
    resources:
        chain:
          strategy:
            content:
              enabled: true
              paths: /**
    datasource:
        druid:
#            primary:
#                url: jdbc:oracle:thin:@//134.96.127.227:1521/CTZJRRS
#                username: RPT_WEB
#                password: x84yan
            primary:
                  url: jdbc:oracle:thin:@//134.96.83.50:1521/pgbb
                  username: yw_zdm
                  password: zdm_20171212
            secondary:
                url: jdbc:oracle:thin:@//134.96.83.50:1521/pgbb
                username: borpt
                password: borpt_1004
            initial-size: 1
            min-idle: 1
            max-active: 20
            max-wait: 20000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            filter: stat,wall
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            use-global-data-source-stat: true
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: root
                login-password: root
                reset-enable: false
            web-stat-filter:
                enabled: true
                exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
              
   
    redis:
        database: 10
        host: 134.96.246.24
        port: 8084
        timeout: 15000
        password: root
        pool:
            max-active: 10
            max-idle: 10
            max-wait: 15000
            min-idle: 2



#mybatis:
#    type-aliases-package: com.loushuiyifan.common.bean
#    mapper-locations: classpath*:mapper/**/*.xml
#    configuration:
#        map-underscore-to-camel-case: true    # 驼峰命名转换

mapper:
    mappers:
        - com.loushuiyifan.config.mybatis.MyMapper
    not-empty: false
    before: true

pagehelper:
    helperDialect: oracle
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    page-size-zero: true
    auto-runtime-dialect: true



